[build]
  publish = "exampleSite/public"
  command = "cd exampleSite && hugo --gc --themesDir ../.. --config config-prod.toml"

[build.environment]
  HUGO_VERSION = "0.54.0"
  HUGO_THEME = "repo"
 [[plugins]]
  package = "netlify-plugin-image-optim"
[[plugins]]
package = "netlify-plugin-subfont"
[build]
  publish = "public"

[[plugins]]
  package = "netlify-plugin-submit-sitemap"

	[plugins.inputs]

	# The base url of your site (optional, default = main URL set in Netlify)
	baseUrl = "https://savets.org"

	# Path to the sitemap URL (optional, default = /sitemap.xml)
	sitemapPath = "/sitemap.xml"

	# Enabled providers to submit sitemap to (optional, default = 'google', 'bing', 'yandex'). Possible providers are currently only 'google', 'bing', 'yandex'.
	providers = [
		"google",
		"bing",
		"yandex"
	]
[[build]]
  functions = functions # must specify a functions folder for this to work
[[plugins]]
  package = netlify-plugin-search-index
    # all inputs is optional, we just show you the defaults below
    # [plugins.inputs]
      # ignore = ["/ignore-this-file.html"] # don't index this file
      # generatedFunctionName = search # change the name of generated folder in case of conflicts, use `null` to turn off
      # publishDirJSONFileName = searchIndex # also use null to turn off

[[plugins]]
package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  buildDir = "public"
