baseURL = "http://localhost:1313/"
disableKinds = ["taxonomy", "taxonomyTerm", "section"]
disqusShortname = ""
googleanalytics = ""
languageCode = "en-us"
theme = "hugo-theme-massively"
title = "The Savets"
[languages.en]
languageName = "English"
