baseURL = "http://localhost:1313/"
disableKinds = ["taxonomy", "taxonomyTerm", "section"]
disqusShortname = ""
googleanalytics = ""
languageCode = "en-us"
theme = "hugo-theme-massively"
title = "Massively"
[languages.en]
languageName = "English"
[languages.es]
languageName = "Español"
title = "Massively - Versión Español"
