baseURL = "https://www.savets.org/"
disableKinds = ["taxonomy", "taxonomyTerm", "section"]
disqusShortname = ""
googleanalytics = ""
languageCode = "en-us"
theme = "hugo-theme-massively"
title = "The Savets"
[languages.en]
languageName = "English"
live_base_url = "https://www.savets.org"
